image: registry.fvdh.dev/gradle:6.7-jdk11

stages:
  - build
  - staticAnalysis
  - test

build:
  stage: build
  script:
    gradle build

checkStyle:
  stage: staticAnalysis
  script:
    gradle build checkstyleMain checkStyleTest

PMD:
  stage: staticAnalysis
  script:
    gradle build pmdMain pmdTest

test:
  stage: test
  script:
    gradle build test
